server:
  port: 8801
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.221.78:8848
      config:
        server-addr: 192.168.221.78:8848
        file-extension: yaml
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
          filters:
            StripPrefix=0
    loadbalancer:
      ribbon:
        enabled: false
  config:
    import:
      - optional:nacos:gateway.yaml
##openFeign整合sentinel熔断
feign:
  sentinel:
    enabled: true