server:
  port: 8003
spring:
  application:
    name: consumer
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.221.78:8848
      config:
        server-addr: 192.168.221.78:8848
        file-extension: yaml
    loadbalancer:
      ribbon:
        enabled: false
  config:
    import:
      - optional:nacos:consumer.yaml
  kafka:
    consumer:
      group-id: testGroup
##openFeign整合sentinel熔断
feign:
  sentinel:
    enabled: true