server:
  port: 8004
  tongweb:
    license:
      path: classpath:icense.dat
spring:
  application:
    name: provide
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yaml
    loadbalancer:
      ribbon:
        enabled: false
  config:
    import:
      - optional:nacos:provide.yaml
##openFeign整合sentinel熔断
feign:
  sentinel:
    enabled: true


