# DataSource Config
spring:
  redis:
  #单机模式
#    #redis数据库索引，默认0
#    database: 0
#    #redis数据库地址
#    host: localhost
#    port: 6379
#    password: root
#    lettuce:
#      pool:
#        max-active: 8
#        max-idle: 8
#        min-idle: 0
#        max-wait: 1000ms
#      shutdown-timeout: 1000ms
#    timeout: 5000ms
  #集群模式
    cluster:
      nodes: 130.1.14.125:6049,130.1.14.126:6049,130.1.14.127:6049,130.1.14.128:6049,130.1.14.129:6049,130.1.14.130:6049
      max-redirects: 3  # 获取失败 最大重定向次数
    password: rxtd@123

#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*Mapper.xml
  # pojo包地址，多个使用逗号隔开，不能使用*和classpath
  #type-aliases-package: com.zdinit.icecream.sys.vo
  configuration:
    #输出格式化sql，但是结果也会输出，过于庞大
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl





client:
  ip: 127.0.0.1
  port: 5000

