--时间状态表
CREATE TABLE CD_RUNSTATE
(ID BIGINT PRIMARY KEY,
 RS_CURDATE DATE,
 RS_SYSSTATE VARCHAR(255),
 RS_RMRK VARCHAR(255),
 RS_WORKDATE DATE
);
--机构表
CREATE TABLE SYS_GROUP
(ID BIGINT PRIMARY KEY,
 GROUP_NAME VARCHAR(255),
 GROUP_CODE VARCHAR(255),
 PID BIGINT,
 STATE INT
);
--资源表
CREATE TABLE SYS_RESOURCE
(ID BIGINT PRIMARY KEY,
 RESOURCE_CODE VARCHAR(255),
 RESOURCE_NAME VARCHAR(255),
 PID BIGINT,
 ORDERS INT,
 TYPE INT,
 LEAF INT
);
--角色表
CREATE TABLE SYS_ROLE
(ID BIGINT PRIMARY KEY,
 ROLE_NAME VARCHAR(255),
 STATE INT
);
--用户表
CREATE TABLE SYS_USER
(ID BIGINT PRIMARY KEY,
 USERNAME VARCHAR(255),
 PASSWORD VARCHAR(255),
 SHOW_NAME VARCHAR(255),
 MOBILE VARCHAR(255),
 EMAIL VARCHAR(255),
 CREATE_TIME DATE,
 LAST_LOGIN_TIME DATE,
 LOGIN_COUNT INT,
 GROUP_ID BIGINT,
 STATE INT,
 FOREIGN KEY(GROUP_ID) REFERENCES SYS_GROUP(ID)
);
--用户角色表
CREATE TABLE SYS_USER_ROLE
(USER_ID BIGINT NOT NULL,
 ROLE_ID BIGINT NOT NULL,
 PRIMARY KEY(USER_ID,ROLE_ID),
 FOREIGN KEY(USER_ID) REFERENCES SYS_USER(ID),
 FOREIGN KEY(ROLE_ID) REFERENCES SYS_ROLE(ID)
);
--角色资源表
CREATE TABLE SYS_ROLE_RESOURCE
(ROLE_ID BIGINT NOT NULL,
 RESOURCE_ID BIGINT NOT NULL,
 PRIMARY KEY(ROLE_ID,RESOURCE_ID),
 FOREIGN KEY(RESOURCE_ID) REFERENCES SYS_RESOURCE(ID),
 FOREIGN KEY(ROLE_ID) REFERENCES SYS_ROLE(ID)
);

--test Index table
CREATE TABLE t_index_table
(ID BIGINT PRIMARY KEY,
 GROUP_NAME VARCHAR(255),
 GROUP_CODE VARCHAR(255),
 PID BIGINT,
 STATE INT,
 USERNAME VARCHAR(255),
 PASSWORD VARCHAR(255),
 SHOW_NAME VARCHAR(255),
 MOBILE VARCHAR(255),
 EMAIL VARCHAR(255),
 CREATE_TIME DATE,
 LAST_LOGIN_TIME DATE,
 LOGIN_COUNT INT,
 GROUP_ID BIGINT
);